apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-db-backup
spec:
  schedule: "0 0 * * *"   # Every night at 00:00 (Midnight)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-agent
            image: busybox
            command: ["/bin/sh", "-c", "echo 'Backing up Database... Done!'"]
          restartPolicy: OnFailure
