apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-backend     # Matches the template label below
  template:
    metadata:
      labels:
        app: mysql-backend   # The label assigned to the Pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Admin@123" 
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: internal-db-svc
spec:
  type: ClusterIP      
  selector:
    app: mysql-backend # Finds the pods matching the Deployment template label
  ports:
    - protocol: TCP
      port: 3306       # Service port
      targetPort: 3306 # Container port
