apiVersion: v1
kind: Pod
metadata:
  name: billing-api-pod
  labels:
    app: billing        # Label Key: app, Value: billing
    environment: prod   # Label Key: environment, Value: prod
spec:
  containers:
    - name: api
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing        # Selector looking for the matching label
    environment: prod   # Selector looking for the matching label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
