apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    env: 
      - name: The_color
        valueFrom:            
          configMapKeyRef:
            name: app-config
            key: APP_COLOR  
      - name: My_SQL_PWD
        valueFrom:            
          secretKeyRef:
            name: db-pass
            key: password        
  restartPolicy: Always
